---
galaxy_info:
  role_name: arch_install
  author: Antti
  description: Bare metal Arch Linux installation role for legacy BIOS systems
  company: 
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - archlinux
    - installation
    - baremetal
    - system

dependencies: []

collections:
  - community.general
  - ansible.posix

